spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:\Users\veraa\Documents\Repositories\configuracion-data-taller2
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000
